name: Deploy site to pages

on:
  push:
    branches: ['main']

# Required permissions for actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Artifact to GitHub Pages
        uses: actions/deploy-pages@v4

